apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqlserver.fullname" . }}
  labels:
    app: {{ include "sqlserver.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sqlserver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sqlserver.name" . }}
    spec:
      containers:
      - name: sqlserver
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc