apiVersion: v1
kind: Service
metadata:
  name: mssql-loadbalancer
spec:
  type: NodePort
  selector:
    app: {{ include "sqlserver.name" . }}
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433