replicaCount: 1

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2019-latest

service:
  type: ClusterIP
  port: 1433

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

secret:
  saPassword: Your_Password123